<?php

namespace AppBundle\Repository;

/**
 * AuctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuctionRepository extends \Doctrine\ORM\EntityRepository
{
}
