<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Auction;

/**
 * AuctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuctionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findActiveOrdered()
    {
        return $this
            ->createQueryBuilder("a")
            ->where("a.status = :active")
            ->setParameter("active", Auction::STATUS_ACTIVE)
            ->andWhere("a.expiresAt > :now")
            ->setParameter(":now", new \DateTime())
            ->orderBy("a.expiresAt", "ASC")
            ->getQuery()
            ->getResult();
    }
}
